version : '3.8'

services:
  student:
    build: .
    container_name: docker-practice
    volumes:
        - .:/app
    command: python app/main.py

  tests:
    build: .
    container_name: docker_tests
    volumes:
      - .:/app
    command: pytest